# Generated by Django 4.1.13 on 2024-11-02 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('vietnamese', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('examples', models.JSONField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
