# Generated by Django 4.1.13 on 2024-11-06 06:48

import CapApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='_id',
            field=models.CharField(default=CapApp.models.generate_uuid, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='examples',
            field=models.JSONField(),
        ),
    ]
