# Generated by Django 4.1.13 on 2024-11-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0002_alter_vocabulary__id_alter_vocabulary_examples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='examples',
            field=models.JSONField(),
        ),
    ]
