# Generated by Django 4.1.13 on 2024-11-06 07:25

import CapApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0004_remove_vocabulary_examples'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.CharField(default=CapApp.models.generate_uuid, max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
