# Generated by Django 4.1.13 on 2024-11-07 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0006_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vietnamese', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='category',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='CapApp.topic'),
        ),
    ]
