# Generated by Django 4.1.13 on 2024-11-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0007_topic_remove_vocabulary_category_vocabulary_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='topic',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='CapApp.topic'),
        ),
    ]
