# Generated by Django 4.1.13 on 2024-11-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0013_remove_vocabulary_topic_vocabulary_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='category',
        ),
    ]
