# Generated by Django 4.1.13 on 2024-11-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0014_remove_vocabulary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='topic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
