# Generated by Django 4.1.13 on 2024-11-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0015_vocabulary_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default='123456', max_length=6),
        ),
    ]
